### ISSUE TITLE
setup.py wants to open non-existing file

### ISSUE THREAD

**Issue by 0-wiz-0** [mplewis/csvtomd#10]
setup.py has:
`with open('README.rst') as f:`
but there is no such file. I guess it means to use `README.md`.

**Comment by mplewis** [comment]
Hey @0-wiz-0 – Sorry for the long delay getting back to you.

This is an artifact of the way I have csvtomd building. You'll need to use `setup_wrap.py` instead of `setup.py`. It builds the RST file from the MD readme, then runs the base `setup.py`.

Let me know if you have any other questions.

**Comment by 0-wiz-0** [comment]
I just tried running `setup_wrap.py`. It didn't run for me because it wanted `pypandoc` which is a wrapper for `pandoc` which is written in Haskell. So to run it we need to install a complete different language. I think that's quite a heavy dependency.
My suggestion: please include the generated `README.rst` file in the distribution tarballs uploaded to pypi, because the file is static anyway. It is not necessary that every installation of `csvtomd` generates this file from scratch again, that can be done once when packaging a release.
Thanks.

**Comment by mplewis** [comment]
I will definitely consider it. Right now the build script isn't properly generating the RST file anyway, so I'm also considering just moving from Markdown to RST. Thanks for the suggestion – I'll keep you posted when I resolve this.

**Comment by cheusov** [comment]
8 years after. Extremely heavy haskel dependency is still in source code. Could you please generate .rst file and make it part of distribution?

**Comment by mplewis** [comment]
@cheusov This Python project is discontinued. Please see the other projects listed in the readme.
