### ISSUE TITLE
support delimiter of tab '\t'

### ISSUE THREAD

**Issue by infinite-Joy** [mplewis/csvtomd#19]
Support the entry of delimiter of TAB. The user should be able to run the below command

csvtomd mycsv.csv -d '\t'

**Comment by splaisan** [comment]
you can do it with _-d '<kbd>Tab</kbd>'_
to get <kbd>Tab</kbd> you need to type <kbd>Ctrl</kbd> + V together then <kbd>Tab</kbd> alone
I made it a custom bash function (into ~/.bash_functions sourced in my .bashrc) to ease the process (the space between '' is a tab)

```
tsvtomd () 
{ 
    csvtomd -d '        '
}
```

great tool by the way, thanks @mplewis

**Comment by pansapiens** [comment]
I have a PR that adds support for `\t` as a delimiter here: https://github.com/mplewis/csvtomd/pull/25

**Comment by mplewis** [comment]
Hi @infinite-Joy and @splaisan,

Thanks so much for posting a workaround!

I am sorry for taking so long to get back to this issue. At this time I'm not continuing development on the Python version of this tool.

I'm moving work to the following JS projects:

* [csvtomd lib](https://github.com/mplewis/csvtomd-lib)
* [csvtomd CLI](https://github.com/mplewis/csvtomd-cli)
* [csvtomd web](https://github.com/mplewis/csvtomd-web)

I'm happy to point to your projects if you decide to take over development on the Python version! Just let me know.
