### ISSUE TITLE
IndexErrors occur when files with uneven row-length are parsed

### ISSUE THREAD

**Issue by kevana** [mplewis/csvtomd#2]
Example file contents:

```
a,b,c
d,e
f,g,h
```

Traceback:

```
Traceback (most recent call last):
  File "./csvtomd.py", line 126, in <module>
    print(md_table(csv, padding=args.padding))
  File "./csvtomd.py", line 79, in md_table
    row[cell_num] = pad_to(cell, col_sizes[cell_num])
IndexError: list index out of range
```

**Comment by mplewis** [comment]
Yep. We can fix this in two ways:
- Pad rows to the max row length with empty strings
- Close as not an issue and yell at the user

I like the idea of padding rows to make sure we work even if the table is kinda malformed.

**Comment by mplewis** [comment]
This has been taken care of by #4.
