### ISSUE TITLE
would it be possible to issue a version for python 2.x

### ISSUE THREAD

**Issue by splaisan** [mplewis/csvtomd#24]
Working on a mac, 2.7 is the default and adding python 3 is not straightforward.
Is there a lot of code that would not work with v2 (not a python programmer)
Thanks in advance

**Comment by mplewis** [comment]
Hi @splaisan,

I actually made the conscious decision when building this package to support only Python 3, as the Python 2 end-of-life date had already been selected at the time.

If it helps, I recommend installing Python 3 via Homebrew as described in the [Hitchhiker's Guide](https://docs.python-guide.org/starting/install3/osx/) – it's the easiest way I have found to get started in Python 3 on Mac.

Hope this helps!
