### ISSUE TITLE
Not getting the latest version

### ISSUE THREAD

**Issue by OolonColoophid** [mplewis/csvtomd#9]
Hi there

I'm pretty new to github, so please forgive me if this is a silly question, but I've installed csvtomd using the included instructions and have received this version:

`Metadata-Version: 2.0
Name: csvtomd
Version: 0.1.1
Summary: Convert your CSV files into Markdown tables.
Home-page: https://github.com/mplewis/csvtomd
Author: Matthew Lewis
Author-email: matt@mplewis.com
Installer: pip
License: MIT
Location: /usr/local/lib/python3.5/site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Natural Language :: English
  License :: OSI Approved :: MIT License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Topic :: Text Processing :: Markup
Entry-points:
  [console_scripts]
  csvtomd = csvtomd:main`

I've used the 'upgrade' option for pip3 to verify that this is the latest version, and pip3 tells me this is the case. However, when running the command, I get the following:

`usage: csvtomd [-h] [-n] [-p PADDING] csv_file [csv_file ...]`

This is missing the delimiter option that I know has been added. 

I'm obviously doing something wrong! Could you help me out?

Cheers

Ian

**Comment by mplewis** [comment]
Hey Ian! Sorry for the incredibly long delay getting back to you.

You're right, this hasn't been added. I have been neglecting this project, but I'm going to be working on it a bit more lately. I'll make sure to push MASTER to PyPI as soon as possible. Thanks!

**Comment by mplewis** [comment]
OK – latest version is tagged as `0.2.0` and pushed to PyPI. Enjoy. 🍕
